-- Auto-generated by build_papers.py -- do not edit
import DependencyGraph
import Credibility.Basic
import Credibility.CheapTalk
import Credibility.CoherentStopping
import Credibility.CostlySignals
import Credibility.Impossibility
import Credibility.Leverage
import Credibility.Paper4Bridge
import Credibility.Regime

#export_decl_info_json "decls.json"
