import Lake
open Lake DSL

-- SSOT Foundations - Lean 4 Formalization
-- Auto-generated by build_papers.py

def moreServerArgs := #[
  "-Dpp.unicode.fun=true",
  "-Dpp.proofs.withType=false"
]

def moreLeanArgs := moreServerArgs

def weakLeanArgs : Array String :=
  if get_config? CI |>.isSome then
    #["-DwarningAsError=true"]
  else
    #[]

package «paper2_ssot» where
  moreServerArgs := moreServerArgs

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git"

lean_lib «paper2_Basic» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_Bounds» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_CaseStudies» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_Completeness» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_Derivation» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_Foundations» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_LangEvaluation» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_LangPython» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_LangRust» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_LangStatic» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_Languages» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_Requirements» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper2_SSOT» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs
