import Lake
open Lake DSL

-- Credibility - Lean 4 Formalization
-- Auto-generated by build_papers.py

def moreServerArgs := #[
  "-Dpp.unicode.fun=true",
  "-Dpp.proofs.withType=false"
]

def moreLeanArgs := moreServerArgs

def weakLeanArgs : Array String :=
  if get_config? CI |>.isSome then
    #["-DwarningAsError=true"]
  else
    #[]

package «paper5_credibility» where
  moreServerArgs := moreServerArgs

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git"

lean_lib «paper5_Basic» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper5_CheapTalk» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper5_CostlySignals» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper5_Credibility» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper5_Impossibility» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper5_Leverage» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs
