-- Auto-generated by build_papers.py -- do not edit
import Lean
import Lean.Util.FoldConsts
import DecisionQuotient.AlgorithmComplexity
import DecisionQuotient.Basic
import DecisionQuotient.BayesFoundations
import DecisionQuotient.BayesFromDQ
import DecisionQuotient.BayesOptimalityProof
import DecisionQuotient.BayesianBridge
import DecisionQuotient.CheckAxioms
import DecisionQuotient.ClaimClosure
import DecisionQuotient.Complexity
import DecisionQuotient.ComplexityMain
import DecisionQuotient.Computation
import DecisionQuotient.ComputationalDecisionProblem
import DecisionQuotient.CrossPaperDependencies
import DecisionQuotient.DecisionGeometry
import DecisionQuotient.Dichotomy
import DecisionQuotient.Economics.Approximation
import DecisionQuotient.Economics.Elicitation
import DecisionQuotient.Economics.ValueOfInformation
import DecisionQuotient.Finite
import DecisionQuotient.FunctionalInformation
import DecisionQuotient.GraphNontriviality
import DecisionQuotient.HandleAliases
import DecisionQuotient.Hardness.ApproximationHardness
import DecisionQuotient.Hardness.ConfigReduction
import DecisionQuotient.Hardness.CountingComplexity
import DecisionQuotient.Hardness.CoveringLowerBound
import DecisionQuotient.Hardness.ETH
import DecisionQuotient.Hardness.QBF
import DecisionQuotient.Hardness.SAT
import DecisionQuotient.Hardness.Sigma2PExhaustive.AnchorSufficiency
import DecisionQuotient.Hardness.Sigma2PExhaustive.Summary
import DecisionQuotient.Hardness.Sigma2PExhaustive.VectorE_CoNP
import DecisionQuotient.Hardness.Sigma2PHardness
import DecisionQuotient.Hardness
import DecisionQuotient.HardnessDistribution
import DecisionQuotient.Information.RDSrank
import DecisionQuotient.Information.RateDistortion
import DecisionQuotient.Information
import DecisionQuotient.Instances
import DecisionQuotient.IntegrityCompetence
import DecisionQuotient.InteriorVerification
import DecisionQuotient.PhysicalBudgetCrossover
import DecisionQuotient.Physics.AccessRegime
import DecisionQuotient.Physics.AnchorChecks
import DecisionQuotient.Physics.AssumptionNecessity
import DecisionQuotient.Physics.BoundedAcquisition
import DecisionQuotient.Physics.ClaimTransport
import DecisionQuotient.Physics.ConstraintForcing
import DecisionQuotient.Physics.Conversation
import DecisionQuotient.Physics.DecisionEquivalence
import DecisionQuotient.Physics.DecisionTime
import DecisionQuotient.Physics.DiscreteSpacetime
import DecisionQuotient.Physics.HeisenbergStrong
import DecisionQuotient.Physics.Instantiation
import DecisionQuotient.Physics.IntegrityEquilibrium
import DecisionQuotient.Physics.InvariantAgreement
import DecisionQuotient.Physics.LocalityPhysics
import DecisionQuotient.Physics.MeasureNecessity
import DecisionQuotient.Physics.MolecularIntegrity
import DecisionQuotient.Physics.ObserverRelativeState
import DecisionQuotient.Physics.PhysicalCore
import DecisionQuotient.Physics.PhysicalHardness
import DecisionQuotient.Physics.PhysicalIncompleteness
import DecisionQuotient.Physics.TUR
import DecisionQuotient.Physics.TransportCost
import DecisionQuotient.Physics.Uncertainty
import DecisionQuotient.Physics.WassersteinIntegrity
import DecisionQuotient.PolynomialReduction
import DecisionQuotient.QueryComplexity
import DecisionQuotient.Quotient
import DecisionQuotient.Reduction
import DecisionQuotient.Reduction_AllCoords
import DecisionQuotient.Statistics.FisherInformation
import DecisionQuotient.Statistics.ProbabilisticBridge
import DecisionQuotient.StochasticSequential.AlgorithmComplexity
import DecisionQuotient.StochasticSequential.Basic
import DecisionQuotient.StochasticSequential.ClaimClosure
import DecisionQuotient.StochasticSequential.Computation
import DecisionQuotient.StochasticSequential.CrossRegime
import DecisionQuotient.StochasticSequential.Dichotomy
import DecisionQuotient.StochasticSequential.Economics
import DecisionQuotient.StochasticSequential.Finite
import DecisionQuotient.StochasticSequential.Hardness
import DecisionQuotient.StochasticSequential.HardnessDistribution
import DecisionQuotient.StochasticSequential.Hierarchy
import DecisionQuotient.StochasticSequential.Information
import DecisionQuotient.StochasticSequential.Instances
import DecisionQuotient.StochasticSequential.PolynomialReduction
import DecisionQuotient.StochasticSequential.QueryComplexity
import DecisionQuotient.StochasticSequential.Quotient
import DecisionQuotient.StochasticSequential.SubstrateCost
import DecisionQuotient.StochasticSequential.Summary
import DecisionQuotient.StochasticSequential.TemporalIntegrity
import DecisionQuotient.StochasticSequential.TemporalLearning
import DecisionQuotient.StochasticSequential.ThermodynamicLift
import DecisionQuotient.StochasticSequential.Tractability
import DecisionQuotient.StochasticSequential
import DecisionQuotient.Sufficiency
import DecisionQuotient.Summary
import DecisionQuotient.ThermodynamicLift
import DecisionQuotient.ToolCollapse
import DecisionQuotient.Tractability.BoundedActions
import DecisionQuotient.Tractability.Dimensional
import DecisionQuotient.Tractability.FPT
import DecisionQuotient.Tractability.SeparableUtility
import DecisionQuotient.Tractability.StructuralRank
import DecisionQuotient.Tractability.Tightness
import DecisionQuotient.Tractability.TreeStructure
import DecisionQuotient.Tractable
import DecisionQuotient.UniverseObjective
import DecisionQuotient.WitnessCheckingDuality

open Lean System

/-- Collect all constant names referenced in a ConstantInfo's type and value. -/
def collectDeps (info : ConstantInfo) : Array Name :=
  let deps := info.type.foldConsts #[] fun n acc => acc.push n
  match info with
  | ConstantInfo.defnInfo v  => v.value.foldConsts deps fun n acc => acc.push n
  | ConstantInfo.thmInfo v   => v.value.foldConsts deps fun n acc => acc.push n
  | ConstantInfo.opaqueInfo v => v.value.foldConsts deps fun n acc => acc.push n
  | _ => deps

/-- Filter: keep only names from our project namespaces. -/
def isProjectName (n : Name) : Bool :=
  let s := n.toString
  s.startsWith "Leverage" ||
  s.startsWith "Ssot" ||
  s.startsWith "DecisionQuotient" ||
  s.startsWith "AbstractClassSystem"

/-- JSON escape for strings -/
def jsonEscape (s : String) : String :=
  s.replace "\\" "\\\\" |>.replace "\"" "\\\"" |>.replace "\n" "\\n"

/-! ### JSON export for visualization pipeline -/

elab "#export_graph_json" path:str : command => do
  let env ← getEnv
  let filePath := path.getString

  let mut nodes : Array String := #[]
  let mut edges : Array String := #[]

  let entries := (Lean.Environment.constants env).fold
    (init := #[]) fun acc name info => acc.push (name, info)

  for (name, info) in entries do
    if isProjectName name then
      let kind := match info with
        | ConstantInfo.thmInfo _    => "theorem"
        | ConstantInfo.defnInfo _   => "definition"
        | ConstantInfo.axiomInfo _  => "axiom"
        | ConstantInfo.opaqueInfo _ => "opaque"
        | _                         => "other"
      nodes := nodes.push
        s!"\{\"id\":\"{jsonEscape name.toString}\",\"kind\":\"{kind}\"}"

      let deps := collectDeps info
      for d in deps do
        if isProjectName d then
          edges := edges.push
            s!"\{\"source\":\"{jsonEscape name.toString}\",\"target\":\"{jsonEscape d.toString}\"}"

  let json := s!"\{\"nodes\":[{",".intercalate nodes.toList}],\"edges\":[{",".intercalate edges.toList}]}"

  IO.FS.writeFile ⟨filePath⟩ json
  Lean.logInfo m!"Graph exported to {filePath}: {nodes.size} nodes, {edges.size} edges"

#export_graph_json "graph.json"
