import Lake
open Lake DSL

-- Leverage Framework - Lean 4 Formalization
-- Auto-generated by build_papers.py

def moreServerArgs := #[
  "-Dpp.unicode.fun=true",
  "-Dpp.proofs.withType=false"
]

def moreLeanArgs := moreServerArgs

def weakLeanArgs : Array String :=
  if get_config? CI |>.isSome then
    #["-DwarningAsError=true"]
  else
    #[]

package «paper3_leverage» where
  moreServerArgs := moreServerArgs

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git"

lean_lib «paper3_Examples» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper3_Foundations» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper3_LambdaDR» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper3_Leverage» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper3_Probability» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper3_SSOT» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper3_Theorems» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper3_Typing» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper3_WeightedLeverage» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs
