-- Auto-generated by build_papers.py -- do not edit
import Lean
import Lean.Util.FoldConsts
import Ssot.Basic
import Ssot.Bounds
import Ssot.CaseStudies
import Ssot.ClaimClosure
import Ssot.Coherence
import Ssot.Completeness
import Ssot.CrossPaperDependencies
import Ssot.DependencyBridge
import Ssot.Derivation
import Ssot.Dof
import Ssot.EditDynamics
import Ssot.Entropy
import Ssot.Foundations
import Ssot.HandleAliases
import Ssot.Inconsistency
import Ssot.LangEvaluation
import Ssot.LangPython
import Ssot.LangRust
import Ssot.LangStatic
import Ssot.Languages
import Ssot.ObserverModel
import Ssot.Requirements
import Ssot.SSOT
import Ssot.SSOTGrounded

open Lean System

/-- Collect all constant names referenced in a ConstantInfo's type and value. -/
def collectDeps (info : ConstantInfo) : Array Name :=
  let deps := info.type.foldConsts #[] fun n acc => acc.push n
  match info with
  | ConstantInfo.defnInfo v  => v.value.foldConsts deps fun n acc => acc.push n
  | ConstantInfo.thmInfo v   => v.value.foldConsts deps fun n acc => acc.push n
  | ConstantInfo.opaqueInfo v => v.value.foldConsts deps fun n acc => acc.push n
  | _ => deps

/-- Filter: keep only names from our project namespaces. -/
def isProjectName (n : Name) : Bool :=
  let s := n.toString
  s.startsWith "Leverage" ||
  s.startsWith "Ssot" ||
  s.startsWith "DecisionQuotient" ||
  s.startsWith "AbstractClassSystem"

/-- JSON escape for strings -/
def jsonEscape (s : String) : String :=
  s.replace "\\" "\\\\" |>.replace "\"" "\\\"" |>.replace "\n" "\\n"

/-! ### JSON export for visualization pipeline -/

elab "#export_graph_json" path:str : command => do
  let env ← getEnv
  let filePath := path.getString

  let mut nodes : Array String := #[]
  let mut edges : Array String := #[]

  let entries := (Lean.Environment.constants env).fold
    (init := #[]) fun acc name info => acc.push (name, info)

  for (name, info) in entries do
    if isProjectName name then
      let kind := match info with
        | ConstantInfo.thmInfo _    => "theorem"
        | ConstantInfo.defnInfo _   => "definition"
        | ConstantInfo.axiomInfo _  => "axiom"
        | ConstantInfo.opaqueInfo _ => "opaque"
        | _                         => "other"
      nodes := nodes.push
        s!"\{\"id\":\"{jsonEscape name.toString}\",\"kind\":\"{kind}\"}"

      let deps := collectDeps info
      for d in deps do
        if isProjectName d then
          edges := edges.push
            s!"\{\"source\":\"{jsonEscape name.toString}\",\"target\":\"{jsonEscape d.toString}\"}"

  let json := s!"\{\"nodes\":[{",".intercalate nodes.toList}],\"edges\":[{",".intercalate edges.toList}]}"

  IO.FS.writeFile ⟨filePath⟩ json
  Lean.logInfo m!"Graph exported to {filePath}: {nodes.size} nodes, {edges.size} edges"

#export_graph_json "graph.json"
