-- Auto-generated by build_papers.py -- do not edit
import DependencyGraph
import AbstractClassSystem.AxisClosure
import AbstractClassSystem.Bridge
import AbstractClassSystem.Core
import AbstractClassSystem.Extended
import AbstractClassSystem.GraphBridges
import AbstractClassSystem.Typing

#export_decl_info_json "decls.json"
