import Lake
open Lake DSL

-- Decision Quotient - Lean 4 Formalization
-- Auto-generated by build_papers.py

def moreServerArgs := #[
  "-Dpp.unicode.fun=true",
  "-Dpp.proofs.withType=false"
]

def moreLeanArgs := moreServerArgs

def weakLeanArgs : Array String :=
  if get_config? CI |>.isSome then
    #["-DwarningAsError=true"]
  else
    #[]

package «paper4_decision_quotient» where
  moreServerArgs := moreServerArgs

require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git"

lean_lib «paper4_AlgorithmComplexity» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Basic» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Complexity» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_ComplexityMain» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Computation» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_DecisionQuotient» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Dichotomy» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Finite» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Hardness» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Information» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Instances» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_PolynomialReduction» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_QueryComplexity» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Quotient» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Reduction» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Sufficiency» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs

lean_lib «paper4_Tractable» where
  moreLeanArgs := moreLeanArgs
  weakLeanArgs := weakLeanArgs
